sites:
  eder-gmbh:
    origin: https://github.com/techdivision/eds-eder-gmbh
    port: 3001
  eder-landtechnik:
    origin: https://github.com/techdivision/eds-eder-landtechnik
    port: 3002
  agratec-salching:
    origin: https://github.com/techdivision/eds-agratec-salching
    port: 3003
