name: Build
on: [ push, workflow_dispatch ]

jobs:
  build:
    # because this repo is synced to other repositories, we need to specify the repository where we explicitly want this action to run
    if: github.event.repository.name == 'eds-eder-main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
